# Mac-specific Configurations

# Load common tools
# Note: Run 'brew bundle --file=../common/Brewfile' to install common tools

# Mac specific CLI (if any)
# brew "mas"

# Casks (GUI Apps)
cask "antigravity"
cask "font-hackgen-nerd"
cask "google-chrome"
cask "orbstack"
cask "spotify"
cask "visual-studio-code"
cask "vivaldi"
